USE [DW_InfraDB]
GO

--DROP FKs DIMENSION
--Drop FK ADDRESS
IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.FK_STG_ADDRESS_DIM_ADDRESS')
   AND parent_object_id = OBJECT_ID(N'dbo.DIM_Address')
)
  ALTER TABLE DIM_Address DROP CONSTRAINT FK_STG_ADDRESS_DIM_ADDRESS
  
--CLEAR DATA TABLE FOR NEW VALUES--
Truncate table [dbo].[STG_Address]

--RE-CREATE FKs DIMENSION 
--CRIA FK ADDRESS
ALTER TABLE [dbo].[DIM_Address]  WITH NOCHECK ADD  CONSTRAINT [FK_STG_ADDRESS_DIM_ADDRESS] FOREIGN KEY([FK_Id_Address])
REFERENCES [dbo].[STG_Address] ([ID_Address])
GO

ALTER TABLE [dbo].[DIM_Address] NOCHECK CONSTRAINT [FK_STG_ADDRESS_DIM_ADDRESS]
GO

